image:
  file: .gitpod.dockerfile
ports:
- port: 3000
- port: 6080
  onOpen: ignore
- port: 5900
  onOpen: ignore
tasks:
- init: >
    git submodule update --remote &&
    yarn && 
    yarn package-vsix:next
- command: >
    jwm &
    yarn start:browser
github:
  prebuilds:
    branches: false
    addLabel: true
    addBadge: true