image:
  file: .gitpod.dockerfile
ports:
- port: 3000
- port: 6080
  onOpen: ignore
- port: 5900
  onOpen: ignore
tasks:
- init: >
    yarn && yarn package-vsix:next
  command: >
    jwm &
    yarn --cwd browser-app start ../ --hostname=0.0.0.0
github:
  prebuilds:
    branches: false