name: ovsx-solid---publish-vscode-built-in-extensions
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
env:
  NODE_OPTIONS: --max-old-space-size=8192
jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OVSX_PAT: ${{ secrets.OVSX_PAT}}
    steps:
      - uses: actions/checkout@v1
      - run: |
          git submodule init
          git submodule update
        name: Checkout VS Code
      # should be aligned with https://github.com/microsoft/vscode/blob/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/.github/workflows/ci.yml#L108
      - run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0
          sudo cp vscode/build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start
        name: Setup Build Environment
      - uses: actions/setup-node@v4
        with:
          node-version-file: vscode/.nvmrc
      - run: yarn
        name: Install Dependencies
      - run: |
          cd vscode
          git fetch --tags
          cd ..
          yarn checkout-latest-vscode-release
        name: Update vscode Repo and Checkout Latest Official Release
      - run: yarn build:extensions
        name: Bundle Extensions
      - run: yarn package-vsix:latest
        name: Package Solid Version of Extensions
      - run: yarn create-extension-pack:latest
        name: Create built-in extensions pack
      # - run: yarn publish:vsix
      #   name: Publish Extensions to open-vsx.org
